#!/usr/bin/env python

import logging
import time
from argparse import ArgumentParser

from videowall.players import PlayerClient, get_player_platform_strings, player_platform_from_string
from videowall.util import validate_positive_int_argument

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('platform', choices=get_player_platform_strings())
    parser.add_argument('filename')
    parser.add_argument('base_time', type=int)
    parser.add_argument('--spin_rate', type=validate_positive_int_argument, default=1)
    parser.add_argument('--ip', default='127.0.0.1')
    parser.add_argument('--port', type=int, default=11111)

    args = parser.parse_args()

    logging.getLogger().setLevel(logging.DEBUG)

    player = PlayerClient(player_platform_from_string(args.platform))

    player.play(args.filename, args.base_time, args.ip, args.port)

    logging.info("Playing file %s with base time %d", args.filename, args.base_time)

    while player.is_playing():
        logging.info("Position: %.2f", player.get_position() / 1e9)
        time.sleep(1. / args.spin_rate)
