#!/usr/bin/env python

import logging
from argparse import ArgumentParser
from videowall.networking import NetworkingClient

if __name__ == '__main__':
    parser = ArgumentParser()

    parser.add_argument('--ip', default='127.0.0.1')
    parser.add_argument('--broadcast_port', type=int, default=2000)
    parser.add_argument('--buffer_size', type=int, default=1024)

    args = parser.parse_args()

    logging.getLogger().setLevel(logging.DEBUG)

    client = NetworkingClient(args.ip, args.broadcast_port, args.buffer_size)
    while True:
        client.receive_broadcast()
