#!/usr/bin/env python

import logging
from argparse import ArgumentParser
from videowall.players import PlayerServer, PlayerPlatform

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('platform', type=PlayerPlatform, choices=list(PlayerPlatform))
    parser.add_argument('filename')
    parser.add_argument('--ip', default='127.0.0.1')
    parser.add_argument('--port', type=int, default=11111)
    parser.add_argument('--gui', action='store_true')

    args = parser.parse_args()

    logging.getLogger().setLevel(logging.DEBUG)

    PlayerServer(args.platform, args.filename, args.ip, args.port, args.gui).play()
