#!/usr/bin/env python

import collections
import logging
import random
import time
from argparse import ArgumentParser

from videowall.players import get_player_platform_strings, player_platform_from_string, PlayerServer
from videowall.util import validate_positive_int_argument


def random_int(size):
    return random.randint(0, size / 2)


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('platform', choices=get_player_platform_strings())
    parser.add_argument('filename')
    parser.add_argument('--spin_rate', type=validate_positive_int_argument, default=1)
    parser.add_argument('--ip', default='127.0.0.1')
    parser.add_argument('--port', default=2222)
    parser.add_argument('--gui', action='store_true')

    args = parser.parse_args()

    logging.getLogger().setLevel(logging.DEBUG)

    player = PlayerServer(player_platform_from_string(args.platform), args.ip, args.port, args.gui)

    player.play(args.filename)

    logging.info("Playing file %s", args.filename)
    logging.info("Start local client with ./test_player_client --ip %s --port %d %s %s %s",
                 player.get_ip(), player.get_port(), args.platform, player.get_filename(), player.get_base_time())

    while player.is_playing():
        logging.info("Position: %.2f", player.get_position() / 1e9)
        time.sleep(1. / args.spin_rate)
