#!/usr/bin/env python

import logging
from argparse import ArgumentParser
from videowall.players import PlayerServer, get_player_platform_strings, player_platform_from_string

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('platform', choices=get_player_platform_strings())
    parser.add_argument('filename')
    parser.add_argument('--ip', default='127.0.0.1')
    parser.add_argument('--port', type=int, default=11111)
    parser.add_argument('--gui', action='store_true')

    args = parser.parse_args()

    logging.getLogger().setLevel(logging.DEBUG)

    PlayerServer(player_platform_from_string(args.platform), args.filename, args.ip, args.port, args.gui).play()
