#!/usr/bin/env python

import logging
import random
import time
from argparse import ArgumentParser

from videowall.players import Player, get_player_platform_strings, player_platform_from_string
from videowall.util import validate_positive_int_argument

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('platform', choices=get_player_platform_strings())
    parser.add_argument('filename')
    parser.add_argument('--spin_rate', type=validate_positive_int_argument, default=10)

    args = parser.parse_args()

    logging.getLogger().setLevel(logging.DEBUG)

    player = Player(player_platform_from_string(args.platform), args.filename)

    while True:
        player.play(args.filename)

        duration = random.choice([1, 5, 10, 15])
        logging.info("Playing for %d seconds", duration)
        t_start = time.time()
        while time.time() < t_start + duration:
            logging.info("Position: %.2f", player.get_position() / 1e9)
            time.sleep(1. / args.spin_rate)
