#!/usr/bin/env python

import logging
from argparse import ArgumentParser
from videowall.players import PlayerClient, get_player_platform_strings, player_platform_from_string

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('platform', choices=get_player_platform_strings())
    parser.add_argument('filename')
    parser.add_argument('base_time', type=int)
    parser.add_argument('--seek_time', type=int, default=0)
    parser.add_argument('--ip', default='127.0.0.1')
    parser.add_argument('--port', type=int, default=11111)

    args = parser.parse_args()

    logging.getLogger().setLevel(logging.DEBUG)

    PlayerClient(player_platform_from_string(args.platform), args.filename, args.ip, args.port).play(
        base_time=args.base_time,
        seek_time=args.seek_time,
    )
