#!/usr/bin/env python

import logging
import os
from argparse import ArgumentParser

from videowall.client import Client
from videowall.players import get_player_platform_strings, player_platform_from_string
from videowall.util import ip_from_ifname

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('player_platform', choices=get_player_platform_strings())
    parser.add_argument('ifname', choices=os.listdir('/sys/class/net/'))
    parser.add_argument('--verbose', action='store_true')
    parser.add_argument('--broadcast_port', type=int, default=2000)

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    client = Client(ip_from_ifname(args.ifname), player_platform_from_string(args.player_platform), args.broadcast_port)
    try:
        client.run()
    except KeyboardInterrupt:
        client.close()
