#!/usr/bin/env python
import argparse
import logging
import os
from argparse import ArgumentParser

from videowall.client import Client
from videowall.player import get_player_platform_strings, player_platform_from_string
from videowall.util import ip_from_ifname, validate_positive_int_argument, validate_positive_float_argument, get_ifnames

if __name__ == '__main__':
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('player_platform', choices=get_player_platform_strings())
    parser.add_argument('ifname', choices=get_ifnames())
    parser.add_argument('--media_path', default=os.path.join(os.path.dirname(os.path.realpath(__file__)), "../videos"))
    parser.add_argument('--verbose', action='store_true')
    parser.add_argument('--server_broadcast_port', type=validate_positive_int_argument, default=2000)
    parser.add_argument('--server_play_broadcast_port', type=validate_positive_int_argument, default=2001)
    parser.add_argument('--client_broadcast_port', type=validate_positive_int_argument, default=3000)
    parser.add_argument('--client_broadcast_interval', type=validate_positive_float_argument, default=1.)

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    client = Client(player_platform_from_string(args.player_platform), args.media_path, ip_from_ifname(args.ifname),
                    args.server_broadcast_port, args.server_play_broadcast_port, args.client_broadcast_port,
                    args.client_broadcast_interval)
    try:
        client.run()
    except KeyboardInterrupt:
        client.close()
