#!/usr/bin/env python

import logging
import time
from argparse import ArgumentParser

from tqdm import tqdm
from videowall.player import get_player_platform_strings, player_platform_from_string, PlayerServer
from videowall.util import validate_positive_int_argument, validate_ip

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('platform', choices=get_player_platform_strings())
    parser.add_argument('filename')
    parser.add_argument('--base_time_offset', type=validate_positive_int_argument, default=5000000000)
    parser.add_argument('--spin_rate', type=validate_positive_int_argument, default=1)
    parser.add_argument('--ip', type=validate_ip, default='127.0.0.1')
    parser.add_argument('--port', type=validate_positive_int_argument, default=11111)
    parser.add_argument('--verbose', action='store_true')

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    player = PlayerServer(player_platform_from_string(args.platform), args.ip, args.port)

    player.play(args.filename, args.base_time_offset)

    logging.info("Playing file %s", args.filename)
    logging.info("Start local client with: ./player_client --ip %s --port %d %s %s %s",
                 player.get_ip(), player.get_port(), args.platform, player.get_filename(), player.get_base_time())

    with tqdm(total=player.get_duration_seconds(),
              bar_format='Playing: {l_bar}{bar} | {n_fmt}/{total_fmt}') as progress_bar:
        while player.is_playing():
            progress_bar.update(player.get_position_seconds() - progress_bar.n)
            try:
                time.sleep(1. / args.spin_rate)
            except KeyboardInterrupt:
                break

    player.close()
