#!/usr/bin/env python


import sys
from players import MasterPlayer
from gi.repository import GObject
import json

import time
import threading
import select
import socket


class MasterThread(threading.Thread):
    def __init__(self, uri, broadcast_port, player_ip, player_port):
        super(MasterThread, self).__init__()
        self.master_player = MasterPlayer(uri, player_ip, player_port)
        self.broadcast_port = broadcast_port

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
        self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)

    def send_update(self):
        pdu = {
            'base-time': self.master_player.base_time,
            'uri': self.master_player.uri,
            'player-ip': self.master_player.ip,
            'player-port': self.master_player.port,
        }
        self.socket.sendto(json.dumps(pdu), ('<broadcast>', self.broadcast_port))

    def run(self):
        self.master_player.play()
        while True:
            self.send_update()
            time.sleep(1)


from argparse import ArgumentParser

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument('uri')
    parser.add_argument('--broadcast_port', type=int, default=37020)
    parser.add_argument('--player_ip', default='localhost')
    parser.add_argument('--player_port', type=int, default=11111)

    args = parser.parse_args()

    GObject.threads_init()
    loop = GObject.MainLoop()

    master = MasterThread(args.uri, args.broadcast_port, args.player_ip, args.player_port)
    master.start()

    loop.run()
