#!/usr/bin/env python3
import collections
import json
import logging
import time
from argparse import ArgumentParser

from tqdm import tqdm
from videowall.server import Server
from videowall.util import validate_positive_int_argument, ip_from_ifname, validate_positive_float_argument, get_ifnames

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('ifname', choices=get_ifnames())
    parser.add_argument('--media_path', default='~/Videos')
    parser.add_argument('--base_time_offset', type=validate_positive_float_argument, default=0.1)
    parser.add_argument('--spin_rate', type=validate_positive_int_argument, default=5)
    parser.add_argument('--server_broadcast_port', type=validate_positive_int_argument, default=2000)
    parser.add_argument('--server_play_broadcast_port', type=validate_positive_int_argument, default=2001)
    parser.add_argument('--server_clock_port', type=validate_positive_int_argument, default=11111)
    parser.add_argument('--server_broadcast_interval', type=validate_positive_float_argument, default=0.2)
    parser.add_argument('--server_init_time', type=validate_positive_float_argument, default=0.5)
    parser.add_argument('--client_broadcast_port', type=validate_positive_int_argument, default=3000)
    parser.add_argument('--client_time_overlay', action='store_true')

    parser.add_argument('--verbose', action='store_true')
    parser.add_argument('--client_config', type=json.loads, default='{}')

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    server = Server(args.media_path, args.base_time_offset, ip_from_ifname(args.ifname), args.server_broadcast_port,
                    args.server_play_broadcast_port, args.server_clock_port, args.server_broadcast_interval,
                    args.client_broadcast_port, args.client_config)

    filenames = collections.deque(server.get_media_filenames())

    # Obtain a client list
    time.sleep(args.server_init_time)

    client_remote_media_paths = ["{}@{}:{}".format(c.username, c.ip, c.media_path) for c in server.get_clients()]
    server.sync_media(client_remote_media_paths)

    while True:
        try:
            filename = filenames[0]
            logging.info("Playing file %s", filename)

            server.play(filename, args.client_time_overlay)

            with tqdm(total=server.get_duration(),
                      bar_format='Playing: {l_bar}{bar} | {n_fmt}/{total_fmt}') as progress_bar:
                while server.is_playing():
                    progress_bar.update(server.get_position() - progress_bar.n)
                    time.sleep(1. / args.spin_rate)

            filenames.rotate()
        except KeyboardInterrupt:
            break

    server.close()
